
name: Pac-Man GitHub Contribution Graph

on:
  schedule: # todo dia às 00h
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Pac-Man SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Yestochi
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg
